services:
  - type: web
    name: prescription-summarizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false